services:
    frontend:
        image: frontend_deploy
        build:
            context: ./frontend
            dockerfile: Dockerfile.prod
        ports:
            - "80:3000"
        depends_on:
            - backend

    backend:
        image: backend_deploy
        build: ./backend
        ports:
            - "81:5000"
